# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tryDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(594, 407)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(230, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(False)
        self.title.setObjectName("title")
        self.questionView = QtWidgets.QGraphicsView(self.centralwidget)
        self.questionView.setGeometry(QtCore.QRect(70, 100, 461, 141))
        self.questionView.setObjectName("questionView")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(250, 280, 91, 31))
        self.startButton.setObjectName("startButton")
        self.titledec = QtWidgets.QLabel(self.centralwidget)
        self.titledec.setGeometry(QtCore.QRect(130, 50, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.titledec.setFont(font)
        self.titledec.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titledec.setAlignment(QtCore.Qt.AlignCenter)
        self.titledec.setObjectName("titledec")
        self.studentLbl = QtWidgets.QLabel(self.centralwidget)
        self.studentLbl.setGeometry(QtCore.QRect(440, 10, 121, 20))
        self.studentLbl.setText("")
        self.studentLbl.setTextFormat(QtCore.Qt.PlainText)
        self.studentLbl.setObjectName("studentLbl")
        self.numberLabel = QtWidgets.QLabel(self.centralwidget)
        self.numberLabel.setGeometry(QtCore.QRect(560, 10, 21, 20))
        self.numberLabel.setText("")
        self.numberLabel.setObjectName("numberLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "SIPENULIS"))
        self.startButton.setText(_translate("MainWindow", "START"))
        self.titledec.setText(_translate("MainWindow", "Sistem Penilaian Ujian Lisan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
